"use client";
import MenuDesktop from "./components/MenuDesktop";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./components/Header";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "700"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const weather: string = "sunny-day";
  const backgroundWeatherGradients: string[] = [
    "bg-gradient-to-b from-sunny-day-blue to-sunny-day-red bg-no-repeat",
    "bg-black",
  ];
  let background = "";
  if (weather === "sunny-day") {
    background = backgroundWeatherGradients[0];
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={background} style={{ height: "100vh" }}>
          <Header />
          <main>{children}</main>
          <MenuDesktop />
        </div>
      </body>
    </html>
  );
}
